<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
		<title>ZOE</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
		<script src="js/jquery_min.js"></script>
		<script src="js/myjscode.js"></script>
		<script language="javascript" type="text/javascript" src="js/flot/jquery.flot.min.js"></script>
		<script language="javascript" type="text/javascript" src="js/flot/jquery.flot.time.js"></script>
		<script language="javascript" type="text/javascript" src="js/flot/jquery.flot.resize.js"></script>
		<script language="javascript" type="text/javascript" src="js/flot/flot_nav/lib/jquery.flot.navigate.js"></script>
		<script language="javascript" type="text/javascript" src="js/flot/flot_nav/jquery.flot.navigationControl.js"></script>
		<link rel="stylesheet" type="text/css" href="styles_screen.css">
		<link rel="stylesheet" type="text/css" media="screen and (max-width: 750px)" href="styles_mobile.css">
	  <link rel="shortcut icon" href="icons/favicon.ico" type="image/x-icon" />
	  <link rel="apple-touch-icon" href="icons/apple-touch-icon.png" />
	  <link rel="apple-touch-icon" sizes="57x57" href="icons/apple-touch-icon-57x57.png" />
	  <link rel="apple-touch-icon" sizes="72x72" href="icons/apple-touch-icon-72x72.png" />
	  <link rel="apple-touch-icon" sizes="76x76" href="icons/apple-touch-icon-76x76.png" />
	  <link rel="apple-touch-icon" sizes="114x114" href="icons/apple-touch-icon-114x114.png" />
	  <link rel="apple-touch-icon" sizes="120x120" href="icons/apple-touch-icon-120x120.png" />
	  <link rel="apple-touch-icon" sizes="144x144" href="icons/apple-touch-icon-144x144.png" />
	  <link rel="apple-touch-icon" sizes="152x152" href="icons/apple-touch-icon-152x152.png" />
	  <link rel="apple-touch-icon" sizes="180x180" href="icons/apple-touch-icon-180x180.png" />
	</head>
	<body>
		<div class="wrapper">


